---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      initContainers:
        - name: sysctl
          image: busybox:1.36
          securityContext:
            privileged: true
          command:
            [
              "sh",
              "-c",
              "sysctl -w net.ipv4.conf.all.src_valid_mark=1 net.ipv6.conf.all.disable_ipv6=1"
            ]
      containers:
        - name: qbittorrent
          image: hotio/qbittorrent:release-4.6.3
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: PGID
              value: '1000'
            - name: PUID
              value: '1000'
            - name: TZ
              value: America/New_York
            - name: VPN_ENABLED
              value: "true"
            - name: VPN_CONF
              value: "wg0"
          ports:
            - containerPort: 8080
              name: qbittorrent
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-data
            - mountPath: /config/wireguard
              name: wireguard
            - mountPath: /data/downloads
              name: nfs-share
      volumes:
        - name: qbittorrent-data
          persistentVolumeClaim:
            claimName: qbittorrent-pvc
        - name: nfs-share
          nfs:
            server: nas01.bubylou.com
            path: /srv/share/Downloads
        - name: wireguard
          secret:
            secretName: wireguard
            items:
              - key: mullvad
                path: wg0.conf
