---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: torrent
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - secret-sealed.yaml
  - service.yaml
