---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - name: dashy
          image: ghcr.io/lissy93/dashy:3.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: production
          ports:
            - name: dashy
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - node
                - /app/services/healthcheck
            initialDelaySeconds: 240
            periodSeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          volumeMounts:
            - name: config
              mountPath: /app/user-data
      volumes:
        - name: config
          configMap:
            name: dashy-config
            items:
              - key: config
                path: conf.yml
