---
apiVersion: v1
kind: Service
metadata:
  name: dashy
spec:
  selector:
    app: dashy
  ports:
    - port: 8080
      protocol: TCP
      targetPort: dashy
  sessionAffinity: None
  type: ClusterIP
