---
apiVersion: v1
kind: Service
metadata:
  name: random
  labels:
    app: random
spec:
  selector:
    app: random
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  sessionAffinity: None
  type: ClusterIP
