---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    ldap-toml: AgBVUTdveaEYXXJe0ZOvNL5MFgSUfbYvwa7b+0Hmg5K484gwX84bzt/jIriJKEREbdtzB9RVCLPoTyrt6ghroyfv2UQOkXs5GTwxmI8vb1JsS5IQqO0OBpPqFAT/TpJLiw0pl1oZop7fBHkkMf54Zum32IMlJSod0uT2WKC97Io6yj7aCyrhSD1tXVoGxmvJRt0X6NodkvOEUK88FZ4goGgTkyIT1tTEoTMK7HQOFs/L3ZaNJ9wilvohsDsndzHDqlQFA/Ps2qnbaphQ/hzwKdC/jsgU1XnuDX9Dc5ldRV07S1c9OdBqc7/JeWiU3QubM9+DNqj+68sHtksVLeMdqkMHYwHvm2vERBxQFLDfXbKitXA8e2Jx3uBkUMqfDpy9UrvKipG5yRdhp+m1KG35SthK2FqENZfiN89J06VlNRCMXINIVAbTxdcpcsJ73yEzczyrrSf5ahr9wMgBR/SBWZid8UN6YABqJPDtssVpMU4ssxymzSlRKZ4jiUdCXrJ02nWq7iNTeXvg+gq5SK0ZoceOG9veRWhrS0jgMMf1FYAIqp3a8Doi11sPYNFX6Ylw5Ka4telsB/zQsANZ1SpMS6kUndqiMzx2sVNcRvFM0u9B1peHQdzLjXgkQpQMd8qmzzwMnzhZyPVyMJniGLv6j+GyVPW/WAruMHJXkV2goxODgIjRvXt9Eu+HG+UOzYWzga8nQcB6qI1KdJHKRTP2Kvvp6kmabpPYov2l8jA9mnPoECdm9AbMB5e/OHEg+s3D2T9qsKps/WYQyxgyaBtIE1LxOm4PWKMQYhcp6l+zii9PZ740VH7VyMqbYifkeaZBGcWKK8g7jIIGY/MbzhXwOtSPOxbxILm3TBpYoe9uKMcrcEU/xzajtZW4bPI449NLWfObrANrZYY3o6qhAzfhaRtpAW8E9l909f8SpmoiF1ELI8GDkO7VGEOhgdsu06sZu5kXsOeeUI52uV2q3GZ7fK1jIOcE1coTaIckQd/PSBJXBboQ+zdeBwhvJCze+8q9GByLAYy1SbhvKiJ1b+kA2jcp6Yi8MjEaO1wvq9Cy11ZhnVs/ffm4cH1Nh3Kzh3l18MRk2aqAJqMs0ESrd+huysvDgBnBrEiV7ZAHKdpd2+ZYL8wDOi9Yk2uYUDXCQGOzCl4qXSxJsGE16p6E1yZzCX8zbwBTPlfg7AnvC3beESa9G7hEko3Q32QEPABzwtRb1gca2RqnOEN0pN6amOBBDFhcZljowoJccuGkBWrAAZI1vhvq9qi98taRwUhmelzHFsLJuy+y44EtykYyIQh/LUws96EQ2MKfFKIkGVkAtQ1Gr/aLMKfKNGdKotkCDi7j0/us3wrtXnEvOjt/HwFcKoFDmg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque
