theme: dark
default_redirection_url: https://bubylou.com/
default_2fa_method: webauthn

server:
  address: 'tcp://:9091/'
  asset_path: '/config/assets/'
  disable_healthcheck: false

log:
  level: info
  keep_stdout: false

telemetry:
  metrics:
    enabled: false
    address: 'tcp://:9959/metrics'

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha256
  digits: 8
  period: 60
  skew: 1
  secret_size: 32

webauthn:
  disable: false
  timeout: 60s
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred

duo_api:
  disable: true

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 1m

  ldap:
    address: ldap://lldap.sso.svc:3890
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=bubylou,dc=com
    additional_users_dn: ou=people
    users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    group_search_mode: 'filter'
    permit_referrals: false
    user: uid=admin,ou=people,dc=bubylou,dc=com
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      group_name: cn

password_policy:
  standard:
    enabled: false

  zxcvbn:
    enabled: true
    min_score: 3

privacy_policy:
  enabled: false
  require_user_acceptance: false
  policy_url: ''

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
      - '10.0.0.0/8'
      - '192.168.0.0/18'

  rules:
    # bypass
    - domain: 'bubylou.com'
      policy: bypass
    - domain_regex: '(blog|jellyfin|random)\.bubylou\.com$'
      policy: bypass
    - domain_regex: '(gonic|navidrome)\.bubylou\.com$'
      policy: bypass
      resources:
        - '^/rest/.*$'
    - domain: 'kuma.bubylou.com'
      policy: bypass
      resources:
        - '^/api/status-page/.*$'
        - '^/assets/index.*$'
        - '^/icon.svg$'
        - '^/status$'
        - '^/status/$'
    - domain_regex: '(bazarr|lidarr|prowlarr|radarr|readarr|sonarr)\.bubylou\.com$'
      policy: bypass
      resources:
      - "^/api/.*$"
    - domain: 'qbittorrent.bubylou.com'
      policy: bypass
      resources:
        - '^/api/v2/.*$'

    # one factor
    - domain_regex: '(dashy|mealie|navidrome|jellyseerr)\.bubylou\.com$'
      policy: one_factor

    # two factor
    - domain_regex: '^.*\.bubylou\.com$'
      policy: two_factor
      networks:
        - internal
      subject:
        - 'group:k3s_admin'
    - domain_regex: '(bazarr|lidarr|prowlarr|radarr|readarr|sonarr)\.bubylou\.com$'
      policy: two_factor
      networks:
        - internal
      subject:
        - 'group:arr_admin'
    - domain: 'qbittorrent.bubylou.com'
      policy: two_factor
      networks:
        - internal
      subject:
        - 'group:arr_admin'
    - domain_regex: '(grafana|kuma|longhorn)\.bubylou\.com$'
      policy: two_factor
      networks:
        - internal
      subject:
        - 'group:k3s_admin'

session:
  cookies:
    - name: authelia_session
      domain: bubylou.com
      authelia_url: 'https://auth.bubylou.com'
      default_redirect_url: 'https://bubylou.com'
      same_site: lax
      inactivity: 5m
      expiration: 1h
      remember_me_duration: 1M
  name: authelia_session
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me_duration: 1M

  redis:
    host: redis-0.redis.sso.svc
    port: 6379
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  postgres:
    address: 'tcp://postgres.sso.svc:5432'
    database: authelia
    schema: public
    username: authelia
    timeout: 5s

notifier:
  disable_startup_check: false
  smtp:
    address: 'smtp://smtp-relay.brevo.com:587'
    timeout: 5s
    username: bubylou@bubylou.com
    sender: "No Reply <no-reply@bubylou.com>"
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: test@authelia.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: 'smtp-relay.brevo.com'
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
