---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sso
resources:
  - deployment.yaml
  - ingress.yaml
  - secret-sealed.yaml
  - service.yaml
  - middleware.yaml
configMapGenerator:
- name: authelia
  namespace: sso
  files:
    - configuration.yml
