---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
spec:
  selector:
    app: lidarr
  ports:
    - port: 8686
      protocol: TCP
      targetPort: http
  sessionAffinity: None
  type: ClusterIP
