---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: game
resources:
  - deployment.yaml
  - pvc.yaml
  - secret-sealed.yaml
  - service.yaml
configMapGenerator:
- name: valheim
  namespace: game
  files:
    - valheim_plus.cfg
