---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-pvc
  labels:
    app: valheim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-mirror-ssd
  resources:
    requests:
      storage: 10Gi
