# https://kubernetes.io/docs/concepts/services-networking/service/
---
apiVersion: v1
kind: Service
metadata:
  name: valheim
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.94
spec:
  selector:
    app: valheim
  type: LoadBalancer
  ports:
    - port: 2456
      targetPort: 2456
      name: valheim
      protocol: UDP
