---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
  labels:
    app: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
