# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    app: postgres
spec:
  storageClassName: longhorn-mirror-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
