# yaml-language-server: kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  labels:
    app: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: navidrome
          image: ghcr.io/navidrome/navidrome:0.51.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ND_REVERSEPROXYUSERHEADER
              value: Remote-User
            - name: ND_REVERSEPROXYWHITELIST
              value: "10.0.0.0/8"
            - name: ND_LASTFM_ENABLED
              value: "true"
            - name: ND_LASTFM_APIKEY
              valueFrom:
                secretKeyRef:
                  name: navidrome
                  key: ND_LASTFM_APIKEY
            - name: ND_LASTFM_SECRET
              valueFrom:
                secretKeyRef:
                  name: navidrome
                  key: ND_LASTFM_SECRET
            - name: ND_SPOTIFY_ID
              valueFrom:
                secretKeyRef:
                  name: navidrome
                  key: ND_SPOTIFY_ID
            - name: ND_SPOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: navidrome
                  key: ND_SPOTIFY_SECRET
          ports:
            - containerPort: 4533
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 4533
              scheme: HTTP
          volumeMounts:
            - mountPath: /data
              name: navidrome-data
            - mountPath: /music
              name: nfs-share
              subPath: Music
      volumes:
        - name: navidrome-data
          persistentVolumeClaim:
            claimName: navidrome-pvc
        - name: nfs-share
          nfs:
            server: nas01.bubylou.com
            path: /srv/share
            readOnly: false
