# https://kubernetes.io/docs/concepts/configuration/configmap/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
data:
  config.yaml: |
    metrics: false

    alerting:
      discord:
        webhook-url: "${DISCORD_WEBHOOK}"
        default-alert:
          enable: true
          description: "health check failed"
          send-on-resolved: true
          failure-threshold: 5
          success-threshold: 5

    connectivity:
      checker:
        target: 1.1.1.1:53
        interval: 5m

    storage:
      type: postgres
      path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.monitoring.svc:5432/${POSTGRES_DB}?sslmode=disable"

    default-endpoint: &defaults
      group: private
      interval: 5m
      conditions:
        - "[STATUS] == 200"
        - "[RESPONSE_TIME] < 100"
      alerts:
        - type: discord

    endpoints:
      - name: domain
        group: public
        url: "1.1.1.1"
        interval: 15m
        dns:
          query-name: "bubylou.com"
          query-type: "A"
        conditions:
          - "[DNS_RCODE] == NOERROR"
        alerts:
          - type: discord
      - name: mealie
        <<: *defaults
        group: public
        url: "http://mealie.home.svc:9000"
      - name: jellyfin
        <<: *defaults
        group: public
        url: "http://jellyfin.media.svc:8096"
      - name: jellyseerr
        group: public
        interval: 5m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
        url: "http://jellyseerr.media.svc:5055"
      - name: navidrome
        <<: *defaults
        group: public
        url: "http://navidrome.music.svc:4533"
      - name: dashy
        <<: *defaults
        group: public
        url: "http://dashy.website.svc:4000"
      - name: random
        <<: *defaults
        group: public
        url: "http://random.website.svc:3000"
      - name: website
        <<: *defaults
        group: public
        url: "http://nginx.website.svc:80"

      - name: domain
        group: private
        url: "192.168.1.91"
        interval: 15m
        dns:
          query-name: "bubylou.com"
          query-type: "A"
        conditions:
          - "[DNS_RCODE] == NOERROR"
        alerts:
          - type: discord
      - name: bazarr
        <<: *defaults
        url: "http://bazarr.arr.svc:6767"
      - name: lidarr
        <<: *defaults
        url: "http://lidarr.arr.svc:8686"
      - name: prowlarr
        <<: *defaults
        url: "http://prowlarr.arr.svc:9696"
      - name: radarr
        <<: *defaults
        url: "http://radarr.arr.svc:7878"
      - name: readarr
        <<: *defaults
        url: "http://readarr.arr.svc:8787"
      - name: sonarr
        <<: *defaults
        url: "http://sonarr.arr.svc:8989"
      - name: qbittorrent
        <<: *defaults
        url: "http://qbittorrent.torrent.svc:8080"
      - name: authelia
        <<: *defaults
        url: "http://authelia.sso.svc:9091"
      - name: lldap
        <<: *defaults
        url: "http://lldap.sso.svc:17170"
      - name: longhorn
        <<: *defaults
        url: "http://longhorn-frontend.longhorn-system.svc:80"
