# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  labels:
    app: gatus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: gatus
          image: twinproduction/gatus:v5.7.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/New_York
          ports:
            - name: gatus-http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: gatus-config
              readOnly: false
      volumes:
        - name: gatus-config
          configMap:
            name: gatus-config
            items:
              - key: config.yaml
                path: config.yaml
