---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-single-hdd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  mkfsParams: ""
  migratable: "false"
  encrypted: "false"
  dataLocality: "disabled"
  replicatAutoBalance: "ignored"
  diskSelector: "hdd"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-single-ssd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  mkfsParams: ""
  migratable: "false"
  encrypted: "false"
  dataLocality: "disabled"
  replicatAutoBalance: "ignored"
  diskSelector: "ssd"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-mirror-ssd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  mkfsParams: ""
  migratable: "false"
  encrypted: "false"
  dataLocality: "disabled"
  replicatAutoBalance: "ignored"
  diskSelector: "ssd"
