---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gonic-cache
  labels:
    app: gonic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gonic-data
  labels:
    app: gonic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-mirror-ssd
  resources:
    requests:
      storage: 5Gi
