# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  labels:
    app: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
