---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mealie
  namespace: home
spec:
  encryptedData:
    LDAP_QUERY_BIND: AgA79dleeTLhjMIQQPzQtVafRiaQ5TnxdpEsiJpbQGSfPHYcw0wJNlB6q6SyyKVRZSBzUlOfpaNauxAUtKySYxcvT+NdS5n8bQWwNBRMEcNqABqk9gKmZ173uDq5VRV6tVPGyr+xrsyjs1lA5g0FI/fyRMHJBUlJ1DzL8vGkSMFTNCycAfapbTm7Wra3n0lPIcpRXtvXr0YlFoTM0Aq+0N/h2pUDX3newJN2kDf10/yk7ICCnVZeRqyj0aJE1p6GXInW1OsN0XOWfVecPfOVPMDcp17FvfHULmhLE8xMrOyTqELnclP8FrGCNVGCHQ4XMzdaPVBGqy7oc44f7AIq0ZGZDyu8eUavGer0o9jPTvIsHHlSznknrvk+4vnbU3xAhBFcQLKp/SdJWn71bv00OmIqT2NUgr5Z/FSm4kdBK0Qazzb5wdbRrbGMCumCbLjsNAbz4Yd8mnw8dDipLounK6meKiny76+RFfiD0KjZi7vO6FvaHmCz9uq71Sk90IqV44DpYFbaUunSqHei0bxNV9mzdDc/+AUo9QrEqBoZoxHAElqHzeryxnRj2TNMNBYwX2evCIlbPhAPPvQAVDbcUv3tBcYTUjLqclCb+OFd5yfrHTvpz4F5yVr9yt/Ty65lkJ3P8aasDEQrPuTbRwuEJJVtDIxUpBoOB9WLjw8E3uJoCPAOjyb0Vwzl0GvNFu1ZZ0upTUQ9mQIJ4XGS/9NlQDXbHXoIR03IJWshuAGSUFKu/LmQ3KBy8es=
    LDAP_QUERY_PASSWORD: AgCMQYx5V00MEYQ+1EQ3Ij0SKnGmHqk6yO4jjwiZV+Cr6EP5Oa8HteH8OEYv/EheJNalVSQvw/bc7R/zbwt8Wy8GKFrUJvvDhCU0hITMdusQw2McPNyY7IaZU4yYhX/qd2fiMECnb/vjUe/Ssi2jhV+fbylIylWeGncP7pnNRSzJ/fCMvyw7ao+aI4e9lBrWFD5FIl3+mBhgC6XJnFyBTc9FzOjegq+fwSi1a2rFxli9GMhd6XDnNd8asJzaXFE3OH7tJ+zjPhytElWtWb2jvf4XB7je2dBuxQnhLc7Cv+zv9aNgU6EKwkZgc7XAVl9FOCvBI2Kb9V/wSy0YWzxNhwI6wCKBTIhqlMNyfeJ7EFwb0/hHfiLnxFhx06ktfcMpxl1/uHLf/N+n3jyh6kbjPb0TxrxkWMgw9l2Qr3sd6bWT2eW5F/drpvAj9NPPnnvXnTFmACNJIzYA2tMmIFWasJm1Z6WggaWGcuE8Q4v7GJ32eDiSTbn1YrzFknhqk48B20OET8+MBapa/p2m/CSU2yTKRud2WurWdWV7+xmgBV8cFHOzvyp1VGImcuhGLOkDxRbbCTaGwDarTTchhvtn+BMXEYPk05C5qMiQZb2p9dvsaeHeLFkM4QBHab8DmpZCzVF6l+ZdoGabAVCE3HIkPem/aKS9ZqN8TMIYrGf/zCvnNW1L5xdajy5pJ5dlFnJJ5Y239JOf5NdHZtjXXSTgSKhv
  template:
    metadata:
      creationTimestamp: null
      name: mealie
      namespace: home
    type: Opaque
