---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mealie
  namespace: home
spec:
  encryptedData:
    LDAP_QUERY_BIND: AgAjhu5CoEy+RIVeLHiPrHx7P0NDpiGHX/Yv5x6Tqgpcd0o1d8I+aQRZ0G+/ADs0tDyij8a8M0TM8EIrNbp7IP152+WbmN6Tvpxdrw6hZRBs6IjFt1Xgk/W2LkPxarkzbzBlwbLNzWJEU/5jPL/eARSewt4acKprECVy6uA5BzsGZBamfhdJum83bbqKkADY+0VK9oVl2WklSjkARph6TjTnX139fuEYuR6/OCf1RNk/JZdLeKHuXHpQVsnzpqT+H1YruwZXTAKniSRcQ+gW14fzYJyo1faSijVObLvoI8yPGZonpcL+kldJ4fwexDUjrb5fg39DE8KdhraIzi8HxlzUDPgHSikVJr2bo63tUw+nVR3gUqOO/diqSIoXPJEhWvqRJ4bQOBf1AlOet5/ZdCnX0nHNBYyd3z9478oPgUouxs9p+c/1Fk2ZO1A+CkXSfOLNow2xVrwneLmbz5TYyvwCMjc90NI/XEBYNaKt6nAcpoU7Dwo82nnCD8/qS0qjvH/yZKumQQFtb0s/n9jwHlMZXxA9mrDU4O7F+E7350doB4jOycM81Shi7A5sIK1yjd/X5KpB2W/3UWdA9PTm9acOz/zpk7sc3t36CMLVpWgV38DY9TWNmCWSmYC5Bz1y1i4o6BWC/nP7DPkbPJtj+cptQopLMlbIxQdMpvzmOerYTERvovUyeqzRWHu8CKloY6Zy4ilyWRXWT+pig/REcnfNNuWYY3Gdacr8w367BYRAVZ0CRGCzw0w=
    LDAP_QUERY_PASSWORD: AgAVY5s3q+wSikDMSvDeYy1B+FwF6DrUdWTQv9QahN2I7aLUgipZ8gEXYDbnCW6bcqg1Ctr3GFjzFJgTbsH1+M0JuUipWNPZR3V+yjkzB/sg4okP0qU6RW1UqFsCWVd3cxHECJwm9vjwB9ev6SZpBiAlxLKbXi7AWpC+EC2rOhc66Q58JMF5KyaPnXn0jmReyjpg8gzCN7vaczKJIPZOP95+TLUHr65Con+mL+8Za62vBMAr77iy6fZLfuyBqifBIVPq9zM11oOQWTpvwLcI/+3aYr+jl5m/41okMWuDJuU9/mUnP/s5Hkpi+mTEQp1QgBblfRbBAJZ7udKx/g517pFCYOfM/us5+bDsIRgHOY9lusWKFVPGDzus3c15nQaDxjf/6Xd/7oBxDY46TDy5oJ6thn+CcfVorNGZrtbxzyEjRsXMll1qUbg4ShI779LaUWCuzItHULXyVQ8ocEXYCxoLIqAwaAOvrPTWKtJwLUzg1eizuHeyfJGw2eCu0XdmkEht2OYIyDdmhfcQx5aYpXJW9SDj8QwrYxTM8jZaeujzdDfL+YqyHMPjYG1MZKMuf+UXpRhybtGIwabzNdH6VCTr71HkQi0tsRaGnvZvzmykYuKUH3iOtEQvcfTIWTI20gJYPReRQsWAHkFgKbJcY5QITWggS9n6VcmM1+H9gqD1XaCuQBgIOONPxtMFUUPeMDSRi5oGwFaaECbn/VS+yF1E
  template:
    metadata:
      creationTimestamp: null
      name: mealie
      namespace: home
    type: Opaque
