---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr-exporter
  labels:
    app.kubernetes.io/name: bazarr-exporter
    app.kubernetes.io/instance: bazarr-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr-exporter
      app.kubernetes.io/instance: bazarr-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bazarr-exporter
        app.kubernetes.io/instance: bazarr-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: bazarr-exporter
          image: ghcr.io/onedr0p/exportarr:v1.5.3
          imagePullPolicy: IfNotPresent
          args:
            - bazarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://bazarr.arr.svc.cluster.local:6767"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: exportarr
                  key: bazarr-api-key
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
