---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-mirror-ssd
  resources:
    requests:
      storage: 5Gi
