# https://kubernetes.io/docs/concepts/services-networking/service/
---
apiVersion: v1
kind: Service
metadata:
  name: bind9
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.91
spec:
  selector:
    app: bind9
  type: LoadBalancer
  ports:
  - port: 53
    targetPort: dns-tcp
    name: dns-tcp
    protocol: TCP
  - port: 53
    targetPort: dns-udp
    name: dns-udp
    protocol: UDP
