---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: bubylou@pm.me
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          email: bubylou@pm.me
          apiTokenSecretRef:
            name: cert-manager
            key: cloudflare-token
      selector:
        dnsZones:
          - "bubylou.com"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bubylou@pm.me
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          email: bubylou@pm.me
          apiTokenSecretRef:
            name: cert-manager
            key: cloudflare-token
      selector:
        dnsZones:
          - "bubylou.com"
