---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  labels:
    app: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-mirror-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
  labels:
    app: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-mirror-ssd
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  labels:
    app: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-single-ssd
  resources:
    requests:
      storage: 50Gi
