---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-pvc
  labels:
    app: navidrome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
