# https://kubernetes.io/docs/concepts/services-networking/service/
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
spec:
  selector:
    app: navidrome
  sessionAffinity: ClientIP
  type: ClusterIP
  ports:
  - port: 4533
    targetPort: 4533
    name: http
    protocol: TCP
