---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-pvc
  labels:
    app: calibre-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
