---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc
  labels:
    app: prowlarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-mirror-ssd
  resources:
    requests:
      storage: 5Gi
