---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  selector:
    app: prowlarr
  ports:
    - port: 9696
      protocol: TCP
      targetPort: http
  sessionAffinity: None
  type: ClusterIP
