---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels:
    app: jellyseerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: jellyseerr
          image: ghcr.io/hotio/jellyseerr:release-1.9.2
          imagePullPolicy: IfNotPresent
          env:
            - name: PGID
              value: '1000'
            - name: PUID
              value: '1000'
            - name: TZ
              value: America/New_York
          ports:
            - containerPort: 5055
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
              scheme: HTTP
          volumeMounts:
            - mountPath: /config
              name: jellyseerr-config
      volumes:
        - name: jellyseerr-config
          persistentVolumeClaim:
            claimName: jellyseerr-pvc
