---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-pvc
  labels:
    app: jellyseerr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-mirror-ssd
  resources:
    requests:
      storage: 5Gi
