# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc
  labels:
    app: bazarr
spec:
  storageClassName: longhorn-mirror-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
