---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  selector:
    app: bazarr
  ports:
    - port: 6767
      protocol: TCP
      targetPort: http
  sessionAffinity: None
  type: ClusterIP
